version: "3"

services:
  backend:
    build: .
    ports:
      - "${PORT}:5000"
    volumes:
      - "./:/usr/src/app"
      - "${DOCKER_STATIC_HOSTING}:/usr/src/app/static"
    environment:
      VIRTUAL_HOST: ${SSL_DOMAIN}
      VIRTUAL_PORT: ${PORT}
      LETSENCRYPT_HOST: ${SSL_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}
      PYTHONIOENCODING: ${PYTHONIOENCODING}
    networks:
      - proxy

networks:
  proxy:
    external:
      name: ${NGINX_PROXY_NETWORK}
