version: "3"

services:
  backend:
    build: .
    container_name: table_api
    ports:
      - "${PORT}:5000"
    volumes:
      - "./:/usr/src/app"
      - "${DOCKER_STATIC_HOSTING}:/usr/src/app/static"
    environment:
      VIRTUAL_HOST: ${SSL_DOMAIN}
      VIRTUAL_PORT: ${PORT}
      LETSENCRYPT_HOST: ${SSL_DOMAIN}
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}
      PYTHONIOENCODING: ${PYTHONIOENCODING}
    networks:
      - https

networks:
  https:
    external:
      name: ${HTTPS_NETWORK}
